function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:23,type:"var"};
this.def["OverrunFlag"] = {file: "ert_main_c.html",line:24,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:25,type:"fcn"};
this.def["stopRequested"] = {file: "ert_main_c.html",line:43,type:"var"};
this.def["main"] = {file: "ert_main_c.html",line:44,type:"fcn"};
this.def["Sine_test_B"] = {file: "Sine_test_c.html",line:22,type:"var"};
this.def["Sine_test_DW"] = {file: "Sine_test_c.html",line:25,type:"var"};
this.def["Sine_test_M_"] = {file: "Sine_test_c.html",line:28,type:"var"};
this.def["Sine_test_M"] = {file: "Sine_test_c.html",line:29,type:"var"};
this.def["SystemProp_matlabCodegenSetAn_p"] = {file: "Sine_test_c.html",line:46,type:"fcn"};
this.def["Sine_test_SystemCore_release_p"] = {file: "Sine_test_c.html",line:52,type:"fcn"};
this.def["Sine_test_SystemCore_delete_p"] = {file: "Sine_test_c.html",line:60,type:"fcn"};
this.def["matlabCodegenHandle_matlabCod_p"] = {file: "Sine_test_c.html",line:66,type:"fcn"};
this.def["SystemProp_matlabCodegenSetAnyP"] = {file: "Sine_test_c.html",line:74,type:"fcn"};
this.def["Sine_test_SystemCore_release"] = {file: "Sine_test_c.html",line:80,type:"fcn"};
this.def["Sine_test_SystemCore_delete"] = {file: "Sine_test_c.html",line:90,type:"fcn"};
this.def["matlabCodegenHandle_matlabCodeg"] = {file: "Sine_test_c.html",line:96,type:"fcn"};
this.def["Sine_test_step"] = {file: "Sine_test_c.html",line:105,type:"fcn"};
this.def["Sine_test_initialize"] = {file: "Sine_test_c.html",line:224,type:"fcn"};
this.def["Sine_test_terminate"] = {file: "Sine_test_c.html",line:342,type:"fcn"};
this.def["B_Sine_test_T"] = {file: "Sine_test_h.html",line:89,type:"type"};
this.def["DW_Sine_test_T"] = {file: "Sine_test_h.html",line:96,type:"type"};
this.def["stm32f769idiscovery_AudioOutp_T"] = {file: "Sine_test_types_h.html",line:28,type:"type"};
this.def["stm32f769idiscovery_AudioInpu_T"] = {file: "Sine_test_types_h.html",line:40,type:"type"};
this.def["P_Sine_test_T"] = {file: "Sine_test_types_h.html",line:45,type:"type"};
this.def["RT_MODEL_Sine_test_T"] = {file: "Sine_test_types_h.html",line:48,type:"type"};
this.def["Sine_test_P"] = {file: "Sine_test_data_c.html",line:20,type:"var"};
this.def["chunk_T"] = {file: "multiword_types_h.html",line:23,type:"type"};
this.def["uchunk_T"] = {file: "multiword_types_h.html",line:24,type:"type"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:27,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:51,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:62,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:86,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:27,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:51,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:25,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:26,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:27,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:28,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:36,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:48,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:54,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:60,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:66,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:37,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:44,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:51,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:47,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:48,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:49,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:50,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:88,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:95,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:102,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:116,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:123,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:130,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:148,type:"type"};
this.def["rtDataTypeSizes"] = {file: "Sine_test_dt_h.html",line:19,type:"var"};
this.def["rtDataTypeNames"] = {file: "Sine_test_dt_h.html",line:39,type:"var"};
this.def["rtBTransitions"] = {file: "Sine_test_dt_h.html",line:59,type:"var"};
this.def["rtBTransTable"] = {file: "Sine_test_dt_h.html",line:71,type:"var"};
this.def["rtPTransitions"] = {file: "Sine_test_dt_h.html",line:77,type:"var"};
this.def["rtPTransTable"] = {file: "Sine_test_dt_h.html",line:82,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["Sine_test_c.html"] = "../Sine_test.c";
	this.html2Root["Sine_test_c.html"] = "Sine_test_c.html";
	this.html2SrcPath["Sine_test_h.html"] = "../Sine_test.h";
	this.html2Root["Sine_test_h.html"] = "Sine_test_h.html";
	this.html2SrcPath["Sine_test_private_h.html"] = "../Sine_test_private.h";
	this.html2Root["Sine_test_private_h.html"] = "Sine_test_private_h.html";
	this.html2SrcPath["Sine_test_types_h.html"] = "../Sine_test_types.h";
	this.html2Root["Sine_test_types_h.html"] = "Sine_test_types_h.html";
	this.html2SrcPath["Sine_test_data_c.html"] = "../Sine_test_data.c";
	this.html2Root["Sine_test_data_c.html"] = "Sine_test_data_c.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "multiword_types_h.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["Sine_test_dt_h.html"] = "../Sine_test_dt.h";
	this.html2Root["Sine_test_dt_h.html"] = "Sine_test_dt_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["mw_cmsis_h.html"] = "../mw_cmsis.h";
	this.html2Root["mw_cmsis_h.html"] = "mw_cmsis_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","Sine_test_c.html","Sine_test_h.html","Sine_test_private_h.html","Sine_test_types_h.html","Sine_test_data_c.html","multiword_types_h.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","Sine_test_dt_h.html","rtmodel_h.html","MW_target_hardware_resources_h.html","mw_cmsis_h.html"];
