function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Test"};
	this.sidHashMap["Test"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/Add"] = {sid: "Test:46"};
	this.sidHashMap["Test:46"] = {rtwname: "<Root>/Add"};
	this.rtwnameHashMap["<Root>/Audio Input"] = {sid: "Test:17"};
	this.sidHashMap["Test:17"] = {rtwname: "<Root>/Audio Input"};
	this.rtwnameHashMap["<Root>/Audio Output"] = {sid: "Test:6"};
	this.sidHashMap["Test:6"] = {rtwname: "<Root>/Audio Output"};
	this.rtwnameHashMap["<Root>/Data Type Conversion"] = {sid: "Test:43"};
	this.sidHashMap["Test:43"] = {rtwname: "<Root>/Data Type Conversion"};
	this.rtwnameHashMap["<Root>/Discrete Filter"] = {sid: "Test:39"};
	this.sidHashMap["Test:39"] = {rtwname: "<Root>/Discrete Filter"};
	this.rtwnameHashMap["<Root>/Discrete Filter1"] = {sid: "Test:44"};
	this.sidHashMap["Test:44"] = {rtwname: "<Root>/Discrete Filter1"};
	this.rtwnameHashMap["<Root>/Discrete Filter2"] = {sid: "Test:45"};
	this.sidHashMap["Test:45"] = {rtwname: "<Root>/Discrete Filter2"};
	this.rtwnameHashMap["<Root>/Gain"] = {sid: "Test:41"};
	this.sidHashMap["Test:41"] = {rtwname: "<Root>/Gain"};
	this.rtwnameHashMap["<Root>/Gain1"] = {sid: "Test:42"};
	this.sidHashMap["Test:42"] = {rtwname: "<Root>/Gain1"};
	this.rtwnameHashMap["<Root>/Gain2"] = {sid: "Test:47"};
	this.sidHashMap["Test:47"] = {rtwname: "<Root>/Gain2"};
	this.rtwnameHashMap["<Root>/Gain3"] = {sid: "Test:48"};
	this.sidHashMap["Test:48"] = {rtwname: "<Root>/Gain3"};
	this.rtwnameHashMap["<Root>/Gain4"] = {sid: "Test:49"};
	this.sidHashMap["Test:49"] = {rtwname: "<Root>/Gain4"};
	this.rtwnameHashMap["<Root>/Matrix Concatenate"] = {sid: "Test:8"};
	this.sidHashMap["Test:8"] = {rtwname: "<Root>/Matrix Concatenate"};
	this.rtwnameHashMap["<Root>/Selector"] = {sid: "Test:19"};
	this.sidHashMap["Test:19"] = {rtwname: "<Root>/Selector"};
	this.rtwnameHashMap["<Root>/Selector1"] = {sid: "Test:38"};
	this.sidHashMap["Test:38"] = {rtwname: "<Root>/Selector1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
